exclude: ^hugo/static/.*$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-xml
        exclude: ^hugo/layouts/sitemap.xml$
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
